### ISSUE TITLE
Validation on Array attributes

### ISSUE THREAD

**Issue by cthurston** [thedersen/backbone.validation#101]
If I'm trying to validate my model on an attribute that is an array, the library seems to fail.  For example if my model requires that at least two members be present, i.e.

```
model.something = ['one','two'];
```

How do I validate that something.length > 1?  

I had to change the flatten function to catch the Array like so:

```
if (val && typeof val === 'object' && !(val instanceof Date || val instanceof RegExp || _.isArray(val))) { ... }
```

I would put in a pull request, but I have no idea if that will break other things.

**Comment by sebafra** [comment]
There is still a problem when you try to validate a multiple select. I´ve to comment this in order to work in flatten:
`if (!!val && _.isArray(val)) {
          // _.forEach(val, function(v, k) {
          //   flatten(v, into, prefix + key + '.' + k + '.');
          //   into[prefix + key + '.' + k] = v;
          // });
        }`
