### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by worldjoe** [thedersen/backbone.validation#180]
I'm using version 0.8.2
I get this error:
Uncaught RangeError: Maximum call stack size exceeded
_.each._.forEach
Backbone.Validation.flatten
(anonymous function)
_.each._.forEach
Backbone.Validation.flatten
(anonymous function)
_.each._.forEach

I made a change in my backbone model to fix the error. My initialize function had this line of code:
    this.bind("change:selfIdentifiedInsuranceKind", this.save)

I changed it to this:
this.bind("change:selfIdentifiedInsuranceKind", this.selfId)

And I created a selfID like so:

  selfId : function(){
    this.save();
  },

This was all in conjunction with backbone.localstorage, so I'm not sure if fetch(), save() was causing issues with backbone.validation. Suffice to say the code change, in my code, above fixed the problem. I'd guess you could reproduce by adding a this.bind with a this.save reference in your own project's model.

**Comment by chiefGui** [comment]
Have you tried with our lastest version? If so, the problem continues?

**Comment by chiefGui** [comment]
Fixed by https://github.com/thedersen/backbone.validation/pull/260.
