### ISSUE TITLE
Question: how to validate a collection?

### ISSUE THREAD

**Issue by cyberval** [thedersen/backbone.validation#181]
I'm rendering a form containing one input type text per model in a collection.
When validating the form I want to check whether all the model are valid and if so save all the models.

How to validate all the models then ?

Thanks a lot for your answer.

Valérian

**Comment by chiefGui** [comment]
```js
_.each(this.collection.models, function (model) {
  model.validate();
});
```

**Comment by platinumazure** [comment]
Also `this.collection.invoke("validate")` will work as well. :-)
