### ISSUE TITLE
Comparing two field values

### ISSUE THREAD

**Issue by james-gardner** [thedersen/backbone.validation#187]
I've got a use case where I need to check for an 'either or' condition. So for example I need there to be either a phone number or email address with data before I make changes to my model.

this.model.preValidate(name, value, valueToCompare);

I can't see there being any way to pass in an extra value to compare against, unless I've missed something in the docs. It seems like a reasonable use case ... though I will leave that open to discussion.

Any thoughts about this?

**Comment by vinikatyal** [comment]
Do these work?
