### ISSUE TITLE
notEqualTo

### ISSUE THREAD

**Issue by bazineta** [thedersen/backbone.validation#190]
While there's an equalTo function available, which is handy for password change form validation, there's not at present a notEqualTo, which is equally handy for password change form validation.  The following seems to work fine:

```
// Add notEqualTo rule to Backbone Validation.

_.extend(Backbone.Validation.validators, {
	notEqualTo: function(value, attr, notEqualTo, model, computed) {
		if (value === computed[notEqualTo]) {
			return this.format('{0} must not be the same as {1}', this.formatLabel(attr, model), this.formatLabel(notEqualTo, model));
        }
    }
});
```

Being a bit new to this, I am unsure if this isn't already present due to some reason that's not obvious to me.  If not, would a PR be welcomed for this?

**Comment by chiefGui** [comment]
Hey @bazineta, answering your old and already resolved question, there's nothing similar built-in yet — but for sure we'll be implementing. Thanks!
