### ISSUE TITLE
Call Backbone.Validation.callbacks methods on individual attr validation

### ISSUE THREAD

**Issue by coyotevz** [thedersen/backbone.validation#205]
When you need to validate only a subset of attrs in the model with model.isValid(attrs), valid/invalid callbacks associated with a view is't called. The only chance to show or hide some elements in the view is validate the entire model.

**Comment by chiefGui** [comment]
Hey guys! Good suggestion!

Basically, I'll update Backbone.Validation for validate just the fields available on the form — what do you think?

**Comment by blikblum** [comment]
@chiefGui
This seems another issue/feature.

The current issue is about valid/invalid events not being triggered. Take a look at the referenced pull request. What is missing in my opinion is a test

**Comment by chiefGui** [comment]
What pull request you are talking about, @blikblum? #244?

**Comment by chiefGui** [comment]
Fixed by https://github.com/thedersen/backbone.validation/pull/271.
