### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by blacksonic** [thedersen/backbone.validation#210]
When having complex objects in attributes it simply crashes.

Validation should skip those attributes which are not present in the validation object and a mechanism should be present to skip flatten for specific attributes, because now it is not possible to validate more complex objects.

**Comment by nuragic** [comment]
Same here... The browser crashes when flatten() is called with a complex object...

:+1:  to @blacksonic suggestion

**Comment by chiefGui** [comment]
Fixed by https://github.com/thedersen/backbone.validation/pull/260.

**Comment by prma85** [comment]
I came on this because I am having this error in the version 0.11.4 :(
