### ISSUE TITLE
equalTo failed

### ISSUE THREAD

**Issue by kiro112** [thedersen/backbone.validation#211]
validation: function() {
			return {
				username: {
					required: true,
					msg: '*'
				},
				password: {
					minLength: 8
				},
				rePassword: {
					equalTo: 'password',
           			msg: 'The passwords does not match'
				},
				name: {
					required: true,
					msg: '*'
				},
				address: {
					required: false,
					msg: '*'
				},
				email: {
					required: true,
					msg: '*'
				}
			};
		}

the rePassword and password is always not match even if it is match
im using Backbone.Validation v0.9.1
with model.preValidate()

**Comment by chiefGui** [comment]
@ragulka is right, the problem only happens on `preValidate`.

Let's continue talking on https://github.com/thedersen/backbone.validation/pull/212.
