### ISSUE TITLE
Set validation options for exact model

### ISSUE THREAD

**Issue by ButuzGOL** [thedersen/backbone.validation#236]
To set options
For example:
Now I should use 
```
Backbone.Validation.configure({
  labelFormatter: 'label'
});
```
So all my models will use this logic 

But I want something like
```
Model.extend({
...
validationOptions: {
  labelFormatter: 'none'
},
...
```
```
...
var formatFunctions = {
  formatLabel: function(attrName, model) {
    var opts = _.extend({}, defaultOptions, model.validationOptions);
      return defaultLabelFormatters[opts](attrName, model);
  },
...
}
...
```
What do you think ?

**Comment by blikblum** [comment]
It's already possible to specify the options through `bind` options argument:

    Backbone.Validation.bind(this.view, {
      labelFormatter: 'none'
    });

**Comment by chiefGui** [comment]
Thanks @blikblum. :+1:
