### ISSUE TITLE
README.md broken link in "this section" for displaying error messages. 

### ISSUE THREAD

**Issue by michaelBenin** [thedersen/backbone.validation#237]
Is there an elegant way to display the error message that is put into the data-error attribute?

The default implementation of the callbacks are a bit naïve, since it is very difficult to make a general implementation that suits everybody.

My recommendation is to override the callbacks and implement your own strategy for displaying the error messages.

Please refer to this section for more details. <---------- "this section"

**Comment by chiefGui** [comment]
The way you show your messages is up to you — Backbone.Validation is responsible to handle with exclusivity the operations of model validation and nothing plus.

Furthermore, two things to highlight it out:

1. 

  > [...] _since it is very difficult to make a general implementation that suits everybody._

    Yeah, you're right. But in any way it's hard to create something that suits everybody — being this "thing" related to technology or not.

2.

  > _My recommendation is to override the callbacks and implement your own strategy for displaying the error messages._

    You're suggesting a interface to handle with messages. Hmmm, I think you made a good shot! @blikblum @platinumazure what do you think?

**Comment by platinumazure** [comment]
@chiefGui I think he's quoting from README.md and saying that an inline link is broken. Is that correct @michaelBenin?

I can dig into this and write a pull request in the next couple of days if you like.

**Comment by michaelBenin** [comment]
Yes @platinumazure you are correct. It's just a broken link. 

"README.md broken link in "this section" for displaying error messages."

**Comment by platinumazure** [comment]
@michaelBenin Thanks for the clarification. Sorry for taking so long to catch on. (In my defense, there were no quotation marks nor Markdown formatting to indicate that it might have been a direct quote.)

@chiefGui I'll take this.

**Comment by chiefGui** [comment]
@platinumazure Same here. Unfortunately, I didn't know the README of the top of my head. And okay, waiting for your update. Thanks! :+1:

**Comment by platinumazure** [comment]
@michaelBenin @chiefGui I've just created pull request #276 to fix this. You can preview it in [my repository][1] (on the `fix-readme-link` branch).

  [1]: https://github.com/platinumazure/backbone.validation/tree/fix-readme-link

**Comment by chiefGui** [comment]
Thank you guys!
