### ISSUE TITLE
Validate group of elements with certain message

### ISSUE THREAD

**Issue by iwarner** [thedersen/backbone.validation#238]
Hiya

Say if all required inputs of the form are empty - I would like to return a single message, is this possible?

**Comment by platinumazure** [comment]
Hi @iwarner,

You can definitely trigger a single message using one of the following two options:

1. Listen to the `validated:invalid` event on the model.

        var MyModel = Backbone.Model.extend({
            validation: { /* validation rules */ }
        });
        _.extend(MyModel.prototype, Backbone.Validation.mixin);

        var MyView = Backbone.View.extend({
            initialize: function () {
                this.model.on("validated:invalid", this.onModelInvalid, this);
            },

            render: function () { /* render */ },

            onModelInvalid: function (model, errors) {
                // This is fired every time a failed validation occurs
                // Clear your single/summary error here
                // Render your single/summary error here
            }
        });

        var view = new MyView({ model: new MyModel() });

2. Use `Backbone.Validation.bind` to bind a model and view and supply callbacks for model being valid or invalid.

        var model = new MyModel();
        var view = new MyView({ model: model });
        Backbone.Validation.bind(view, {
            valid: function () { /* validation was successful */ },
            invalid: function () { /* validation was unsuccessful */ }
        });

Try to see if you can get one of those to work. I like the first approach better, myself, but that's just my preference.

**Comment by chiefGui** [comment]
The first approach suggested by @platinumazure is more semantic. It will work — ping us if I'm wrong.
