### ISSUE TITLE
max and min validators behaves inconsistently 

### ISSUE THREAD

**Issue by pshustad** [thedersen/backbone.validation#242]
The max and min validators used to ensure that a number is within range behave inconsistently as the following snippet (using `Assert.js`)  demonstrates:
```
    assertEquals("Test must be less than or equal to 123",
            Backbone.Validation.validators.max("54,03",'test',123,{}));  // OK 
    assertEquals("Test must be less than or equal to 123",
            Backbone.Validation.validators.max("54,003",'test',123,{}));  // gives undefined

```
Note the use of comma instead of a punctuation separator in the `54,03` strings.
In summary, `54,03` is correctly rejected as a number but `54,003` is incorrectly accepted as a number.

**Comment by platinumazure** [comment]
What's the best way to fix this, anyway? Seems like the proper answer to anything involving number punctuation would require having some internationalization support. (Original poster asserts that `54,03` is not a valid number, which is true in the U.S. and other places, but is false at least in parts of Europe. In some places, comma and decimal/period/full-stop work exactly the opposite from how they do here, so `54,03` is how one would write fifty-four and three-hundredths.)

Personally, I think the smarter thing would be to change the parsing to somehow avoid any punctuation (for now) until some decision is made about internationalization support. But it's not my call.

**Comment by blikblum** [comment]
This library checks if a string is number using defaultPatterns.number. 
"54,003" is interpreted as fifty four thousands which is in accord to US convention.
To not accept such values is a matter of changing the pattern: https://github.com/thedersen/backbone.validation#adding-custom-patterns

So i think this can be closed as the user already can change the behavior to matches its use case

**Comment by platinumazure** [comment]
@blikblum I forgot about custom patterns. Yes, I agree, the user should just override the pattern here. (I think a case could still be made that punctuation should be ignored in the default pattern, but that's a separate issue.)

**Comment by chiefGui** [comment]
@platinumazure the "category" this comes close is a "buggy", but @blikblum pointed well a sweet solution.

I will close since a custom pattern resolves the case. Thank you guys. :smile:
