### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by blikblum** [thedersen/backbone.validation#243]
The last code update has eight months.

Also the issues are not getting responses.

**Comment by thedersen** [comment]
Hi, guys!

First of all, sorry for the silence from my part.

Unfortunately, I can't seem to find the time to work on this project anymore. Partly because I rarely use Backbone these days (switched to React.js). If anyone wants to pick up the work, feel free to fork the repo, and I'll put up a link in the readme. This sounds good?

**Comment by chiefGui** [comment]
@thedersen It sounds. If people approves, I can fork it. Working with Backbone.Validation everyday.

**Comment by richardhinkamp** [comment]
Wouldn't it be better to add another user to this repo to merge pull request etc? This repo is well ranked in search engines, people already know about this one. Creating a second repo would be confusing, event with it mentioned in the readme. Also keeps the current list of issues and pull requests.

**Comment by sergey-dev** [comment]
voting +1 to add another user to the repo, it will have all the benefits specified above. Good input.

**Comment by salarmehr** [comment]
@richardhinkamp  +1

**Comment by chiefGui** [comment]
Well, I agree with the guys. :)

**Comment by SomethingSexy** [comment]
I agree, add more users to this repo.

**Comment by thedersen** [comment]
I agree. @chiefGui Are you up for the task?

**Comment by chiefGui** [comment]
@thedersen I'm on it.

**Comment by thedersen** [comment]
@chiefGui Ok, I've added you as a collaborator on this repo. Godspeed :) If you have a npm user, I can add you there as well?

**Comment by chiefGui** [comment]
@chiefGui on NPM. Feel free to add. :+1: 

I will start to work officially today, at 7pm. In Brazil, now is around 1pm.

**Comment by thedersen** [comment]
@chiefGui Could not find a user with that handle on NPM..

**Comment by chiefGui** [comment]
omfg.. @chiefgui actually.

**Comment by thedersen** [comment]
done

**Comment by salarmehr** [comment]
@chiefGui  Do you plan to merge pull requests?

**Comment by chiefGui** [comment]
@salarmehr Of course I do. Just studying the best way to do it.
