### ISSUE TITLE
pre-validate a hash of attributes returns "undefined"

### ISSUE THREAD

**Issue by andym2009** [thedersen/backbone.validation#249]
I am using the AMD version (in case that is relevant).

For example:

var errors = model1.preValidate('name', 'value'); // works
var errors = model1.preValidate('email', 'foo@example.com'); // works
var errors = model1.preValidate({name: 'value', email: 'foo@example.com'}); // returns "undefined"

validation: function() {
        return {
            name: {
                required: true,
                msg: 'Please enter a name'
            },
            email: {
                required: true,
                pattern: 'email',
                msg: 'Please enter a valid email'
            }}}

**Comment by chiefGui** [comment]
Complex objects should be accepted by `preValidate`, but for now they don't. You can confirm this just seeing the implementation through https://github.com/thedersen/backbone.validation/blob/master/src/backbone-validation.js#L180.

When it is written, the thinking was to preValidate input per input and set your model accordingly the response of input's validation — this is a fallback for now. We are looking for solutions.
