### ISSUE TITLE
Validating complex attribute as a whole

### ISSUE THREAD

**Issue by juodaspaulius** [thedersen/backbone.validation#261]
Lets say the model has attribute which value is complex object such as:

    complex : { 
        one: "val1",
        two: ""
    }

Currently, due to flattening, this attribute can only be validated using validation keys `complex.one` and `complex.two`, but not on a whole object `complex`. What I would really like to do is to specify custom validator on `complex`, for example like this:

    validation: {
        complex: function(val){
              if (val && val.one && val.two){
                   return "Only one of values allowed";
              }
        }
    }

To make it work I minorly modified flatten function to include the key of complex object in addition to other flattened nested keys.
My modified flatten function is:

    var flatten = function (obj, into, prefix) {
        into = into || {};
        prefix = prefix || '';

        _.each(obj, function(val, key) {
            if(obj.hasOwnProperty(key)) {
                if (val && typeof val === 'object' && !(
                    val instanceof Array ||
                    val instanceof Date ||
                    val instanceof RegExp ||
                    val instanceof Backbone.Model ||
                    val instanceof Backbone.Collection)
                ) {
                    flatten(val, into, prefix + key + '.');
                }
                // Removed this else statement so that the key of the complex is always added as well
                // else {
                    into[prefix + key] = val;
                // }
            }
        });

What do you think, perhaps it could be included into the upstream?

**Comment by blikblum** [comment]
I like the idea, this will allow to validate also properties in the middle of the obj path

**Comment by platinumazure** [comment]
Great idea! If no one else wants to, I wouldn't mind writing a pull request and tests for this feature.

**Comment by chiefGui** [comment]
@platinumazure please, do it.

**Comment by blikblum** [comment]
I suggest to merge #260 first to avoid conflicts
