### ISSUE TITLE
Backbone.Model#isValid semantics hidden/broken

### ISSUE THREAD

**Issue by platinumazure** [thedersen/backbone.validation#262]
Hi folks,

I've really enjoyed using this library both in personal and commercial products and it's overall a really great library. However, the library introduces an `isValid` function which is very semantically different from the `Backbone.Model#isValid()` function.

I know it would be a breaking change to fix this, but would it be possible to rename `Backbone.Validation.mixin.isValid` to something else? That way calling `isValid()` on a model would trigger validation and emit `invalid` as needed (...and I think it would also go through the Backbone.Validation logic and emit `validated` and `validated:valid` or `validated:invalid` as well?), and this new function (maybe `isCurrentlyValid()`?) would just check on the current state without running validation.

Given some suggestions on a direction, I would be happy to write up a pull request. At this point, though, I'm not 100% sure what the best approach is here.

Thanks!

**Comment by blikblum** [comment]
You may look at #205

**Comment by platinumazure** [comment]
Hi @blikblum, I don't think that's related. If you look at Backbone's [list of predefined events][1], I'm talking about the `invalid` event listed there.

Basically, the behavior I'm describing can be roughly modeled with this QUnit test:

    test("Backbone's invalid event is triggered if model is invalid without Backbone.Validation mixin", function (assert) {
        // arrange
        var MyModel = Backbone.Model.extend({
            validate: _.constant(true)
        });
        var instance = new MyModel();

        var invalidTriggered = false;
        instance.on("invalid", function () { invalidTriggered = true; });

        // act
        var result = instance.isValid();

        // assert
        assert.ok(!result, "isValid() returns false");
        assert.ok(invalidTriggered, "invalid event was triggered");
    });

    test("Backbone's invalid event is triggered if model is invalid with Backbone.Validation mixin", function (assert) {
        // arrange
        var MyModel = Backbone.Model.extend({
            validation: {
                name: { required: true }
            }
        });
        var instance = new MyModel();

        var invalidTriggered = false;
        instance.on("invalid", function () { invalidTriggered = true; });

        // act
        var result = instance.isValid(true); // to force validation

        // assert
        assert.ok(!result, "isValid() returns false");
        assert.ok(invalidTriggered, "invalid event was triggered");    // <-- this assertion fails
    });

  [1]: http://backbonejs.org/#Events-catalog

**Comment by blikblum** [comment]
I already noticed that the fix in that pull request  fix only half of the issue. I'm working in a new PR to handle both issues callbacks and events

**Comment by chiefGui** [comment]
Fixed by https://github.com/thedersen/backbone.validation/pull/271.
