### ISSUE TITLE
Integrate with Travis CI (or other continuous integration tool)?

### ISSUE THREAD

**Issue by platinumazure** [thedersen/backbone.validation#265]
Just wondering if there is any chance of integrating (or desire to integrate) with Travis CI or some other continuous integration tool? The advantages being that pull requests would have the test suite run on them automatically so it's obvious whether or not the build would work.

**Comment by chiefGui** [comment]
Already discussed on Gitter — coming in a future version.

Thank you to share you thought. :)

**Comment by platinumazure** [comment]
Oops. Thanks for answering at any rate.
