### ISSUE TITLE
Errors messages as object

### ISSUE THREAD

**Issue by Michael758** [thedersen/backbone.validation#267]
Hello !

First of all, thank you for this plugin ! Really really good, probably the best plugin for Backbone validations.

In some frameworks (as PHP Zend Framework), validation returns object (associative array) instead of just a string. The format of this array is:

`{object property that are not valid: {validator name that return error: validator message} }`

Exemple:

`{firsrtname: {required: "Firstname can not be empty."}}`

So you can do some changes in your form behavior (errors displaying, put red border,...)  depending on which validator failed. With current implementation, you can not know which validator failed (or I missed something ;-) )...

Is there a way to do this easily ?

**Comment by chiefGui** [comment]
Hi @Michael758! Very good question!

So, Backbone.Validation sprouts the right error messages natively. It has the capability to know how what to validate and when — but it's up to you designing something in the screen.

I created an example for another user through [this jsFiddle](http://jsfiddle.net/xy1wn130/1/). Check it out!
