### ISSUE TITLE
Software license unclear

### ISSUE THREAD

**Issue by platinumazure** [thedersen/backbone.validation#273]
Just noticing that there's no LICENSE.txt (or similar) file in the repository. In order to avoid potential copyright issues for consumers, it would be good to get one written up.

I noticed the `docco.jst` template implies that the code is released under the MIT license. Would that license be okay or do we need to choose a different one?

If MIT is okay, I can write a pull request to commit a LICENSE.txt (and/or modify README.md) to reflect this. Otherwise, we'll need to choose a license and do the same plus modify `docco.jst` to reflect the new license.

**Comment by chiefGui** [comment]
Coincidentally, I created one [here](https://github.com/thedersen/backbone.validation/blob/master/LICENSE.md). :+1:

**Comment by platinumazure** [comment]
Great, thanks @chiefGui.
