### ISSUE TITLE
Version property out of date

### ISSUE THREAD

**Issue by jacobbuck** [thedersen/backbone.validation#274]
```
> Backbone.Validation.version
< "0.9.1"
```

Not having the correct version number is confusing when testing and debugging.

**Comment by chiefGui** [comment]
Thanks. :+1:

**Comment by jacobbuck** [comment]
@chiefGui https://github.com/thedersen/backbone.validation/blob/2df0fdeee711116ae309fe32210d30827a82f5df/dist/backbone-validation.js#L361

**Comment by chiefGui** [comment]
Just forgot to run `grunt`. Thanks again, @jacobbuck — but it was fixed! :+1:

**Comment by jacobbuck** [comment]
Cool thanks :smile:
