### ISSUE TITLE
Get the name of failed validation rules for an attribute

### ISSUE THREAD

**Issue by keriati** [thedersen/backbone.validation#280]
Currently I can't see any way to get the validation rules that failed for an attribute in a nice way.

If I have in my model:

```
validation: {
   name:            [{required: true}, {maxLength: 35}],
}
```

The model.validate() method will return to me:

```
{
  name: 'Name is required'
}
```

However it would be very nice to also find out which rule failed (in this example 'required'). In our case we want to do more than just display the error messages, however from the message (since we use i18n) we can't know which rule failed.

**Comment by chiefGui** [comment]
Good idea! :+1:

I'm working on this. What do you think of:

```js
{
  name: {
    error: ' required',
    message: 'Name is required'
  }
}
```

**Comment by blikblum** [comment]
error > rule or pattern?

**Comment by chiefGui** [comment]
`rule` is better. :+1:

**Comment by platinumazure** [comment]
Just out of curiosity, how would we handle custom pattern (i.e., regex) validations? How would we handle non-named function validations?

Example of the latter:

    function checkMyField(value, attr, computed) {
        // does something
    }

    var MyModel = Backbone.Model.extend({
        validation: {
            myField: {
                fn: checkMyField      // Note this is a bare function reference
            }
        }
    });

If you're *really* lucky, browsers will detect function names (i.e., function objects have some sort of name property that can be used in `toString()` and similar). Not all browsers will have that.

*Maybe* we can get away with it if we also allow a `rule` or `ruleName` field in the validation structure itself, which would override any "computed" rule name, and if we warn in the docs that rule names will not be auto-generated in some of these circumstances?

**Comment by keriati** [comment]
I like this approach:

```js
{
  name: {
    error: 'required',
    message: 'Name is required'
  }
}
````

However @platinumazure has a point.

If people use **unnamed functions** for validation, they might not need to reuse the validation name, so the error attribute could be **undefined**.

I think using functions directly in the validation definition instead of general rules might be a bad practice, a shortcut. I would consider dropping the support of it and forcing the people to extend Backbone.Validation.validators with a reusable and named method.

In case of **pattern** validation (*regexp*) the error attribute would be 'pattern' I assume and thats okay.
