### ISSUE TITLE
Backbone.Validation.bind() overwrites defined methods on model

### ISSUE THREAD

**Issue by flechto** [thedersen/backbone.validation#291]
I am trying to unit test some code that runs when the model is invalid. In my test I just stub the method before creating the view. When I initialize the view I am calling Validation.bind() and this is overwriting my stubbed method with the validation mixin's method.

MyView.js
````javascript
MyView = Backbone.Model.extend({
    initialize: function () {
        Backbone.Validation.bind(this)
    },
    // more stuff
```
MyView.spec.js
```javascript
beforeEach(function() {
    this.model = { validate: sinon.stub() };
    this.model.validate.returns(/* errors */)
    this.view = new MyView({ model: this.model })
});
it('does stuff', function () {
// do something that causes validation
// my stub is not called
})
```

Looking at the source it does appear that this is intentional but I was wondering what the reason is for this is.
Is there any way around having to implement the validation rules in the test. I am not trying to test if the model is valid but what happens in the view when it is.

**Comment by platinumazure** [comment]
You can work around this by stubbing `Backbone.Validation.bind`:

    sinon.stub(Backbone.Validation, "bind");

Highly recommend using a sandbox object to make it easier to restore stubbed methods during test teardown.

**Comment by flechto** [comment]
Awesome! Thats so simple I love it.
And yea I am using a sandbox. I was just trying to give a quick summary of the problem.

**Comment by platinumazure** [comment]
Awesome, glad to help. No worries re: quick summary, but I had to make sure it was mentioned. Feel free to close this if you're covered. :-)
