### ISSUE TITLE
How can I get the error messages on an invalid model?

### ISSUE THREAD

**Issue by skaterdav85** [thedersen/backbone.validation#293]
```js
var user = new User();
user.isValid(true); // false
```

How can I get the error messages off of user?

**Comment by platinumazure** [comment]
Have you tried `user.validationError?

**Comment by skaterdav85** [comment]
I just tried that and it is returning `null`

**Comment by platinumazure** [comment]
Ah yes, my mistake. We don't set `validationError` in this plugin.

You have two options here. One is to use the `invalid` event and read `options.validationError` there:

    initialize: function () {
        this.model.on("invalid", this.onModelInvalid, this);
    },

    onModelInvalid: function (model, options) {
        // use options.validationError here
    }

Or else you can call the `validate` method:

    var validationErrors = this.model.validate();
    // validationErrors being falsy means validation was successful

**Comment by skaterdav85** [comment]
ok thank you
